#!/usr/bin/env python
"""This takes the ``eiscp-commands.yaml`` file, as generated by
``import_protocol_doc.py``, and writes the ``eiscp.commands`` Python module.
"""

import sys
import os
from datetime import datetime
import yaml
from collections import OrderedDict
import yaml.constructor


# Since we use lists as keys, we need to load them as tuples
def construct_tuple(loader, node):
    return tuple(yaml.SafeLoader.construct_sequence(loader, node))
yaml.SafeLoader.add_constructor('tag:yaml.org,2002:seq', construct_tuple)

# We also need to load mappings in order
# Based on https://gist.github.com/844388
def construct_ordereddict(loader, node):
    data = OrderedDict()
    yield data
    value = construct_mapping(loader, node)
    data.update(value)

def construct_mapping(self, node, deep=False):
    if isinstance(node, yaml.MappingNode):
        self.flatten_mapping(node)
    else:
        raise yaml.constructor.ConstructorError(
            None, None, 'expected a mapping node, but found %s' % node.id, node.start_mark)

    mapping = OrderedDict()
    for key_node, value_node in node.value:
        key = self.construct_object(key_node, deep=deep)
        try:
            hash(key)
        except TypeError as exc:
            raise yaml.constructor.ConstructorError(
                'while constructing a mapping', node.start_mark,
                'found unacceptable key (%s)' % exc, key_node.start_mark)
        value = self.construct_object(value_node, deep=deep)
        mapping[key] = value
    return mapping

yaml.SafeLoader.add_constructor('tag:yaml.org,2002:map', construct_ordereddict)


# Load YAML file
with open(sys.argv[1], 'r') as f:
    data = yaml.safe_load(f)


# Preserve modelsets data before removing from zones
zones = data
modelsets = zones.get('modelsets', {})
del zones['modelsets']

# Generate the Python structures
#
# We want a command dict that does not include the model data, which we
# are not using.
COMMANDS = OrderedDict([
    (zone, OrderedDict([
        (command, {
            **command_data,
            'values': OrderedDict([
                (value, dict(value_data))
                for value, value_data in list(command_data['values'].items())
            ]),
        })
        for command, command_data in commands.items()
    ]))
    for zone, commands in zones.items()
])

# We also want alias mappings to easily allows us to resolve a user command
# to an actual internal command.

# Manually alias the main zone
ZONE_MAPPINGS = {
    # Use main as default zone
    '': 'main',
    None: 'main'
}



def iter_commands_with_aliases(commands):
    for iscp_command, command_data in commands.items():
        yield command_data['name'], iscp_command
        for alias in command_data.get('aliases', []):
            yield alias, iscp_command

COMMAND_MAPPINGS = {
    zone : {
        alias : command
        for alias, command in iter_commands_with_aliases(commands)
    }
    for zone, commands in zones.items()
}


class ValueRange(object):
    def __init__(self, start, end):
        self.start = start
        self.end = end

        self._range = tuple(range(start, end))

    def __contains__(self, value):
        return value in self._range


def find_value_aliases(values):
    """A "command value" or "command argument" in the YAML is defined
    as::

         ISCP_VALUE:
            name: some-user-facing-alias-value
            description: 'foobar'

    ISCP_VALUE can be something static such as "up" or "00", or it
    can be a range, or pattern. Static values can also have aliases:

        ISCP_VALUE:
            name: [the-main-user-facing-alias-value, something-else]
            description: 'foobar'

    This function will return a list of 2-tuples:

        (user-facing-value, iscp_calue)
    """
    for value, data  in values.items():
        # A tuple gives a range, like (0,  100) for the volume
        if isinstance(value, tuple):
            key = ValueRange(*value)
            yield key, value

        # This is a single value with an alias, i.e.
        # key = volume-up, value = UP
        elif 'name' in data:
            key = data['name']
            if not isinstance(key, tuple):
                yield key, value
            else:
                # It's possible that there are multiple aliases
                # for a command
                for item in key:
                    yield item, value
        else:
            # If no alias ('name' key) is set, this indicates that
            # the value is a pattern, like nnnnn
            # We do not support them yet.
            sys.stderr.write('Skipping patterned argument: %s %s\n' % (value, dict(data)))
            continue


VALUE_MAPPINGS = {
    zone : {
        command : {
            alias : value
            for alias, value in find_value_aliases(command_data['values'])
        }
        for command, command_data in list(commands.items())
    }
    for zone, commands in zones.items()
}


# Output format selection
import xml.etree.ElementTree as ET
from xml.dom import minidom

def escape_xml_text(text):
    """Escape special XML characters in text content."""
    if text is None:
        return ""
    return str(text).replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')

def escape_lua_string(text):
    """Escape special characters for Lua strings."""
    if text is None:
        return '""'
    if isinstance(text, (int, float)):
        return str(text)
    text = str(text).replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n').replace('\r', '\\r').replace('\t', '\\t')
    return f'"{text}"'

def format_lua_table(obj, indent=0):
    """Format data structures as Lua tables."""
    spaces = "  " * indent
    
    # Lua reserved keywords that need to be quoted
    lua_keywords = {'and', 'break', 'do', 'else', 'elseif', 'end', 'false', 'for', 
                    'function', 'if', 'in', 'local', 'nil', 'not', 'or', 'repeat', 
                    'return', 'then', 'true', 'until', 'while'}
    
    if isinstance(obj, OrderedDict):
        lines = ['{']
        items = list(obj.items())
        for i, (key, value) in enumerate(items):
            comma = ',' if i < len(items) - 1 else ''
            if isinstance(key, str) and key.isidentifier() and key not in lua_keywords:
                key_str = key
            else:
                key_str = f'[{escape_lua_string(key)}]'
            
            value_str = format_lua_table(value, indent + 1)
            if '\n' in value_str:
                lines.append(f'{spaces}  {key_str} = {value_str}{comma}')
            else:
                lines.append(f'{spaces}  {key_str} = {value_str}{comma}')
        lines.append(f'{spaces}}}')
        return '\n'.join(lines)
    elif isinstance(obj, dict):
        lines = ['{']
        items = list(obj.items())
        for i, (key, value) in enumerate(items):
            comma = ',' if i < len(items) - 1 else ''
            if isinstance(key, str) and key.isidentifier() and key not in lua_keywords:
                key_str = key
            else:
                key_str = f'[{escape_lua_string(key)}]'
            
            value_str = format_lua_table(value, indent + 1)
            lines.append(f'{spaces}  {key_str} = {value_str}{comma}')
        lines.append(f'{spaces}}}')
        return '\n'.join(lines)
    elif isinstance(obj, ValueRange):
        return f'{{ start = {obj.start}, ["end"] = {obj.end}, _type = "range" }}'
    elif isinstance(obj, (list, tuple)):
        if not obj:
            return '{}'
        lines = ['{']
        for i, item in enumerate(obj):
            comma = ',' if i < len(obj) - 1 else ''
            value_str = format_lua_table(item, indent + 1)
            lines.append(f'{spaces}  {value_str}{comma}')
        lines.append(f'{spaces}}}')
        return '\n'.join(lines)
    elif isinstance(obj, str):
        return escape_lua_string(obj)
    elif obj is None:
        return 'nil'
    else:
        return str(obj)

def create_lua_output():
    """Create Lua table representation of the command data."""
    lines = [
        '-- Generated',
        f'--  by {os.path.basename(sys.argv[0])}',
        f'--  from {os.path.basename(sys.argv[1])}',
        f'--  at {datetime.now()}',
        '',
        'local onkyo_commands = {',
        f'  commands = {format_lua_table(COMMANDS, 1)},',
        '',
        f'  modelsets = {format_lua_table(modelsets, 1)},',
        '',
        f'  zone_mappings = {format_lua_table(ZONE_MAPPINGS, 1)},',
        '',
        f'  command_mappings = {format_lua_table(COMMAND_MAPPINGS, 1)},',
        '',
        f'  value_mappings = {format_lua_table(VALUE_MAPPINGS, 1)}',
        '}',
        '',
        'return onkyo_commands'
    ]
    return '\n'.join(lines)

def create_xml_output():
    """Create XML representation of the command data."""
    root = ET.Element('onkyo_commands')
    
    # Add metadata
    metadata = ET.SubElement(root, 'metadata')
    ET.SubElement(metadata, 'generated_by').text = os.path.basename(sys.argv[0])
    ET.SubElement(metadata, 'source_file').text = os.path.basename(sys.argv[1])
    ET.SubElement(metadata, 'generated_at').text = str(datetime.now())
    
    # Add commands
    commands_elem = ET.SubElement(root, 'commands')
    for zone_name, zone_commands in COMMANDS.items():
        zone_elem = ET.SubElement(commands_elem, 'zone', name=zone_name)
        
        for command_code, command_data in zone_commands.items():
            command_elem = ET.SubElement(zone_elem, 'command', code=command_code)
            ET.SubElement(command_elem, 'name').text = escape_xml_text(command_data['name'])
            ET.SubElement(command_elem, 'description').text = escape_xml_text(command_data['description'])
            
            values_elem = ET.SubElement(command_elem, 'values')
            for value_code, value_data in command_data['values'].items():
                if isinstance(value_code, tuple):
                    # Handle range values
                    value_elem = ET.SubElement(values_elem, 'value_range', 
                                             start=str(value_code[0]), end=str(value_code[1]))
                else:
                    value_elem = ET.SubElement(values_elem, 'value', code=str(value_code))
                
                if value_data.get('name'):
                    if isinstance(value_data['name'], tuple):
                        # Multiple aliases
                        aliases_elem = ET.SubElement(value_elem, 'aliases')
                        for alias in value_data['name']:
                            ET.SubElement(aliases_elem, 'alias').text = escape_xml_text(alias)
                    else:
                        ET.SubElement(value_elem, 'name').text = escape_xml_text(value_data['name'])
                
                ET.SubElement(value_elem, 'description').text = escape_xml_text(value_data['description'])
    
    # Add zone mappings
    zone_mappings_elem = ET.SubElement(root, 'zone_mappings')
    for alias, zone in ZONE_MAPPINGS.items():
        mapping_elem = ET.SubElement(zone_mappings_elem, 'mapping')
        ET.SubElement(mapping_elem, 'alias').text = escape_xml_text(str(alias))
        ET.SubElement(mapping_elem, 'zone').text = escape_xml_text(zone)
    
    # Add command mappings
    command_mappings_elem = ET.SubElement(root, 'command_mappings')
    for zone_name, commands in COMMAND_MAPPINGS.items():
        zone_elem = ET.SubElement(command_mappings_elem, 'zone', name=zone_name)
        for alias, command in commands.items():
            mapping_elem = ET.SubElement(zone_elem, 'mapping')
            ET.SubElement(mapping_elem, 'alias').text = escape_xml_text(alias)
            ET.SubElement(mapping_elem, 'command').text = escape_xml_text(command)
    
    # Add value mappings
    value_mappings_elem = ET.SubElement(root, 'value_mappings')
    for zone_name, commands in VALUE_MAPPINGS.items():
        zone_elem = ET.SubElement(value_mappings_elem, 'zone', name=zone_name)
        for command_name, values in commands.items():
            command_elem = ET.SubElement(zone_elem, 'command', name=command_name)
            for alias, value in values.items():
                if isinstance(alias, ValueRange):
                    mapping_elem = ET.SubElement(command_elem, 'range_mapping',
                                               start=str(alias.start), end=str(alias.end))
                    if isinstance(value, tuple):
                        ET.SubElement(mapping_elem, 'range_start').text = str(value[0])
                        ET.SubElement(mapping_elem, 'range_end').text = str(value[1])
                    else:
                        ET.SubElement(mapping_elem, 'value').text = escape_xml_text(str(value))
                else:
                    mapping_elem = ET.SubElement(command_elem, 'mapping')
                    ET.SubElement(mapping_elem, 'alias').text = escape_xml_text(str(alias))
                    ET.SubElement(mapping_elem, 'value').text = escape_xml_text(str(value))
    
    return root

# Determine output format based on command line argument or file extension
output_format = 'xml'  # default
if len(sys.argv) > 2:
    output_format = sys.argv[2].lower()
elif len(sys.argv) > 1:
    # Try to infer from input filename
    input_file = sys.argv[1]
    if input_file.endswith('.yaml') or input_file.endswith('.yml'):
        # Default to XML for YAML input, but can be overridden
        pass

if output_format in ['lua', 'l']:
    # Generate Lua output
    print(create_lua_output())
else:
    # Generate and format XML (default)
    xml_root = create_xml_output()
    xml_string = ET.tostring(xml_root, encoding='unicode')
    
    # Pretty print the XML
    dom = minidom.parseString(xml_string)
    pretty_xml = dom.toprettyxml(indent="  ")
    
    # Remove empty lines and print
    lines = [line for line in pretty_xml.split('\n') if line.strip()]
    print('\n'.join(lines))


